### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by hananeYS** [ermshaua/time-series-segmentation-benchmark#1]
Hello, i I succeeded to run your code. But does your code generated the visualization?

**Comment by ermshaua** [comment]
Hi, 

I just added the code to generate the visualizations of the time series as well as predicted segmentations. Check out the updated README.

Cheers, Arik

**Comment by hananeYS** [comment]
How please to generate all the images for all the dataset, i try this but something was wrong. 

for _, (ts, ts_name, cps, found_cps) in tssb.iterrows():
 import matplotlib.pyplot as plt
 from tssb.utils import visualize_time_series
 fig, ax = visualize_time_series(ts, ts_name, cps, found_cps)
 plt.show()

**Comment by ermshaua** [comment]
The row 

> for _, (ts, ts_name, cps, found_cps) in tssb.iterrows():

is false. TSSB consists of tuples (ts_name, window_size, cps, ts). Try:

```
for _, (ts_name, window_size, cps, ts) in tssb.iterrows():
    fig, ax = visualize_time_series(ts, ts_name, cps)
    plt.savefig(f"images/{ts_name}.png", bbox_inches="tight")
    plt.clf()
```

Cheers, Arik

**Comment by hananeYS** [comment]
> for _, (ts_name, window_size, cps, ts) in tssb.iterrows():
>     fig, ax = visualize_time_series(ts, ts_name, cps)
>     plt.savefig(f"images/{ts_name}.png", bbox_inches="tight")
>     plt.clf()

Thank u, but this is before segmentation prediction, i want after the prediction (found changes points)

**Comment by ermshaua** [comment]
In that case, simply add your predicted change points to the method
```
fig, ax = visualize_time_series(ts, ts_name, cps, found_cps)
```

**Comment by hananeYS** [comment]
> In that case, simply add your predicted change points to the method `fig, ax = visualize_time_series(ts, ts_name, cps, found_cps)`

i did it, but the result was wrong... Like this..
-----for _, (ts_name, window_size, cps, ts) in tssb.iterrows():
    fig, ax = visualize_time_series(ts, ts_name, cps, found_cps)
    plt.savefig(f"tssb/results/{ts_name}.png", bbox_inches="tight")
    plt.clf()-----
 
and this is an example of the result...

![Adiac](https://user-images.githubusercontent.com/30055818/151128676-00215e99-e459-4f49-8c6a-9d40de1b7c30.png)

**Comment by ermshaua** [comment]
Well, is your prediction 
```
found_cps = your_algorithm_predict(ts)
```
in the for loop? And also, can you print your prediction (found_cps)? It seems like it is way too large.

**Comment by ermshaua** [comment]
The following code

```
import numpy as np
import matplotlib.pyplot as plt

from tssb.utils import load_time_series_segmentation_datasets, visualize_time_series
tssb = load_time_series_segmentation_datasets(names=["Adiac"])

for _, (ts_name, window_size, cps, ts) in tssb.iterrows():
    found_cps = np.array([1000])
    fig, ax = visualize_time_series(ts, ts_name, cps, found_cps)
    plt.show()
    plt.clf()
```

leads to the following image:

![Adiac](https://user-images.githubusercontent.com/23294512/151130420-7b5a7ac4-7dbb-4f67-b19b-dcfa673db468.png)

**Comment by hananeYS** [comment]
> I'm sorry, but i tried that, and it's correct juste for Adiac. 
For example, for beetlefly, i got that
![Capture](https://user-images.githubusercontent.com/30055818/151131997-dedcb97c-b70b-4b7e-ac8d-0cf28f7b3028.PNG)

**Comment by ermshaua** [comment]
But this is exactly what you would expect to get for BeetleFly, if your predicted Change Point is at position 1000.

**Comment by hananeYS** [comment]
> But this is exactly what you would expect to get for BeetleFly, if your predicted Change Point is at position 10
 oh yes, i'm stupide.. but how to print for all our predictions, for example like this (but for all images) ... 
 
 
![Capture](https://user-images.githubusercontent.com/30055818/151132890-f54c768d-64ed-4f22-9d21-10e37dd89cfa.PNG)

**Comment by ermshaua** [comment]
Well, you simply predict the CPs in the for loop and save the predicted segmentations.

```
import numpy as np
import matplotlib.pyplot as plt

from tssb.utils import load_time_series_segmentation_datasets, visualize_time_series
tssb = load_time_series_segmentation_datasets(names=["Adiac"])

for _, (ts_name, window_size, cps, ts) in tssb.iterrows():
    found_cps = your_segmentation_algorithm_predict(ts, len(cps))
    fig, ax = visualize_time_series(ts, ts_name, cps, found_cps)
    plt.savefig(f"images/{ts_name}.png", bbox_inches="tight")
    plt.clf()
```

**Comment by hananeYS** [comment]
> Well, you simply predict the CPs in the for loop and save the predicted segmentations.
> 
> ```
> import numpy as np
> import matplotlib.pyplot as plt
> 
> from tssb.utils import load_time_series_segmentation_datasets, visualize_time_series
> tssb = load_time_series_segmentation_datasets(names=["Adiac"])
> 
> for _, (ts_name, window_size, cps, ts) in tssb.iterrows():
>     found_cps = your_segmentation_algorithm_predict(ts, len(cps))
>     fig, ax = visualize_time_series(ts, ts_name, cps, found_cps)
>     plt.savefig(f"images/{ts_name}.png", bbox_inches="tight")
>     plt.clf()
> ```

Yes, now it's okay, thank you very much. This is the final code for your implementation

for _, (ts_name, window_size, cps, ts) in tssb.iterrows():
    found_cps = ClaSPSegmentation(window_size, n_cps=len(cps)).fit_predict(ts)
    fig, ax = visualize_time_series(ts, ts_name, cps, found_cps)
    plt.savefig(f"tssb/results/{ts_name}.png", bbox_inches="tight")
    plt.clf()

**Comment by ermshaua** [comment]
Yes! You are welcome!
