### ISSUE TITLE
Where does the ground truth changepoint indexes come from? 

### ISSUE THREAD

**Issue by erickalfaro** [ermshaua/time-series-segmentation-benchmark#2]
Hello!

In this library I noticed that there are only a couple of multivariate data sets available. 

I understand that the source of all this data is [UEA & UCR time series classification](http://timeseriesclassification.com/). Since they've expanded the multivariate section to ~30 data sets I was hoping to also find the ground truth changepoints associated to those data sets. 

In this library I see that the change point ground truth comes from this [desc.txt](https://github.com/ermshaua/time-series-segmentation-benchmark/blob/main/tssb/datasets/desc.txt) file. 

Would you be so kind as to point me in the direction of how I can derive these ground truth segments for more data sets found on [UEA & UCR time series classification](http://timeseriesclassification.com/)?

**Comment by ermshaua** [comment]
Hi @erickalfaro,

yes, we have not extended TSSB to multivariate TS yet. However, we actually plan to do so in the future. In the meantime, you can look into the [Dataset Generation Notebook](https://github.com/ermshaua/time-series-segmentation-benchmark/blob/main/tssb/notebooks/dataset_generation.ipynb) and see how the TSSB TS are created. 

The ArrowHead example in that notebook illustrates the pipeline. There we use the [generate_time_series_segmentation_dataset](https://github.com/ermshaua/time-series-segmentation-benchmark/blob/main/tssb/utils.py) method which groups TS by labels and then concatenates them. The points at which the different classes are concatenated are derived as the ground truth change points.

Cheers, Arik
