### ISSUE TITLE
multi-dimension data

### ISSUE THREAD

**Issue by caozhenxiang** [ermshaua/time-series-segmentation-benchmark#3]
Hi, 

Thank you for providing this package. I successfully installed it. However, it seems can not deal with multi-channel inputs. When I feed a 5-dimensional time series, I get an error.

Thank you for your reply in advance.

**Comment by ermshaua** [comment]
The time series segmentation benchmark is currently limited to univariate time series data (as are ClaSP and ClaSS). If you are interested in multivariate time series segmentation, please check out: https://github.com/patrickzib/human_activity_segmentation_challenge This repo contains multivariate time series as well as examples of how to segment them.

Best regards
Arik

**Comment by caozhenxiang** [comment]
Thank you for your fast reply. Another question is about the result. I observed that the algorithm can return a list of detected change points for univariate time series data. However, the majority of ground truth change points are missed. Do you have any suggestions for the reason and solution? Many thanks!

**Comment by ermshaua** [comment]
My suggestion is to tune the parameters for you data. I have a notebook on that for the ClaSP algorithm: https://github.com/ermshaua/claspy/blob/main/claspy/notebooks/clasp_configuration.ipynb Also check out the ablation studies in my papers. They discuss the influence of parameters in detail.

**Comment by caozhenxiang** [comment]
Thanks for sharing this.
